apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: frontend-canary-health
  namespace: stratomesh
spec:
  metrics:
    - name: frontend-available-pods
      interval: 10s
      count: 3
      successCondition: result[0] >= 1
      failureLimit: 1
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          query: |
            sum(kube_pod_status_ready{namespace="stratomesh",condition="true",pod=~"stratomesh-frontend-.*"})
