apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stratomesh-frontend-canary
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - stratomesh
  selector:
    matchLabels:
      monitoring: stratomesh-frontend-canary
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
