apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stratomesh-ingress
  namespace: stratomesh
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stratomesh-frontend
                port:
                  number: 8080
