name: terraform-ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.9"

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend needed)
        working-directory: envs/dev
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: envs/dev
        run: terraform validate

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Checkov
        run: pip install checkov

      - name: Checkov scan
        run: checkov --config-file .checkov.yaml
